FONT = ../fonts/5x7-dot-matrix/5x7-dot-matrix.otf
FONTSIZE = 12
BG = "\#cccc00"
FG = black
BORDER = 4

ALL =	images/cmd-new.png \
		images/cmd-cload-annuity.png \
		images/prompt-N.png images/input-N.png \
		images/prompt-I.png images/input-I.png \
		images/prompt-PV.png images/input-PV.png \
		images/prompt-PMT.png \
		images/prompt-FV.png images/input-FV.png \
		images/result-PMT-1.png \
		images/enter-V-1600.png \
		images/result-V-1600-N.png \
		images/result-V-1600-N12.png \
		images/enter-N-120.png \
		images/result-FV-120.png \
		images/set-PV-minus-30k.png \
		images/reset-FV-0.png \
		images/approx-N-no-idea.png \
		images/approx-N-184.png \




all:	$(ALL)

clean:
	rm -f $(ALL)

images/cmd-new.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"NEW                     " \
			$@

images/cmd-cload-annuity.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"CLOAD \"ANNUITY\"         " \
			$@

images/prompt-N.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"N:                      " \
			$@

images/input-N.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"30*12                   " \
			$@

images/prompt-I.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"I:                      " \
			$@

images/input-I.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"5.5/12                  " \
			$@

images/prompt-PV.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"PV:                     " \
			$@

images/input-PV.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"250000                  " \
			$@

images/prompt-PMT.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"PMT:                    " \
			$@

images/prompt-FV.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"FV:                     " \
			$@

images/input-FV.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"0                       " \
			$@

images/result-PMT-1.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"PMT=             1419.46" \
			$@

images/enter-V-1600.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"V=1600                  " \
			$@

images/result-V-1600-N.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"N=                275.39" \
			$@

images/result-V-1600-N12.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"N/12=              22.95" \
			$@

images/enter-N-120.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"Z=120                   " \
			$@

images/result-FV-120.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"FV=            206352.48" \
			$@

images/set-PV-minus-30k.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"C=B-30000               " \
			$@

images/reset-FV-0.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"B=0                     " \
			$@

images/approx-N-no-idea.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"APPROX N:               " \
			$@

images/approx-N-184.png:
	convert -background $(BG) -fill $(FG) \
			-font $(FONT) -pointsize $(FONTSIZE) \
			-bordercolor $(BG) -border $(BORDER)x$(BORDER) \
			label:"N=                184.27" \
			$@



